# Generated by Django 6.0.2 on 2026-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancerous', 'Cancerous'), ('non-cancerous', 'Non-cancerous'), ('in_review', 'In Review')], default='pending', max_length=20),
        ),
    ]
